
POST http://localhost:3001/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0MmEzYzgwZi1lNWRlLTRlZjUtODg1NS04NWY2YzFiNWY4N2MiLCJpYXQiOjE3MjEyMzg2MTgsImV4cCI6MTcyMTI0MjIxOH0.U01OlI9bK9f4NJOCXB3L5vk8TwWWK1-6TF4jpRhmchs

{
    "caption": "안녕",
    "clothing_infos": [],
    "hashtags": [],
    "photo_urls" : ["data:image/png"]
}

###

GET http://localhost:3001/clothing?query=나이키&start=1