export const styleImages = [
	{ category: 'luxury', id: 0, src: '/styles/classic.jpg' },
	{ category: 'casual', id: 1, src: '/styles/casual.jpg' },
	{ category: 'street', id: 2, src: '/styles/hip.jpg' },
	{ category: 'feminine', id: 3, src: '/styles/feminine.jpg' },
	{ category: 'hip', id: 4, src: '/styles/luxury.jpg' },
	{ category: 'outdoor', id: 5, src: '/styles/street.jpg' },
	{ category: 'casual', id: 6, src: '/styles/feminine.jpg' },
	{ category: 'classic', id: 7, src: '/styles/hip.jpg' },
	{ category: 'sporty', id: 8, src: '/styles/casual.jpg' },
	{ category: 'formal', id: 9, src: '/styles/formal.jpg' },
	{ category: 'feminine', id: 10, src: '/styles/luxury.jpg' },
	{ category: 'street', id: 11, src: '/styles/street.jpg' },
	{ category: 'minimal', id: 12, src: '/styles/casual.jpg' },
	{ category: 'outdoor', id: 13, src: '/styles/classic.jpg' },
	{ category: 'formal', id: 14, src: '/styles/formal.jpg' },
	{ category: 'sporty', id: 15, src: '/styles/outdoor.jpg' },
	{ category: 'hip', id: 16, src: '/styles/hip.jpg' },
	{ category: 'minimal', id: 17, src: '/styles/minimal.jpg' },
	{ category: 'classic', id: 18, src: '/styles/classic.jpg' },
	{ category: 'luxury', id: 19, src: '/styles/luxury.jpg' },
];
